limesurvey:
    build:
      # Hint: Change it to 3.0/apache/ if you want to use LimeSurvey 3.*
      context: 6.0/apache/
      dockerfile: Dockerfile
    volumes:
      # Hint: This is just an example, change /tmp to something persistent
      - /tmp/upload/surveys:/var/www/html/upload/surveys
    ports:
      # Hint: Change it to 80:8080 if you are using LimeSurvey 3.*
      - "8082:8080"
    environment:
      - DB_TYPE=pgsql
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    external: true
    name: app_network
